def print_room_img(room):
	if room["name"] == "the White House":
		print("                                                                     `                                                                ")
		print("                                                                     :+/                                                              ")
		print("                                                                     :`.                                                              ")
		print("                                                                    `/.                                                               ")
		print("                                                               `.:+osyyo+/-`                                                          ")
		print("                                                     `-//oyyyhdddddddddddddddhyyys+/:.                                                ")
		print("                                                `-/+osyyhdddddddddddddddddddddddddhyyys+/:.                                           ")
		print("                                             .++oooyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysoo++/                                        ")
		print("      /o++++++++ooo+++++++ooo+++++++ooo++++++ohdy++++++++++++/oooooooooooo+oo++/+++/+++++++ddy+//+++ooo+++++++ooo++++++/+ooo+++++++oo`")
		print("      sdhssssssydddssssosydddysssoosdddhsosssohd+.............--------:::--::..............ydysossssdddysssssohddhssssssydddssssosydd.")
		print("     .oyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyys/..+yyyyyyyyyy+..:syyyyyyyy+..-syyyyyyyyys-.-oyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy:")
		print("     .oyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy+  hdddhhdddddh` odddddddddd. /ddddddddddd/ .yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy:")
		print("      sddddddddddddddddddddddddddddddddddddddddo  hhhddddddddh` +dddddddddh. /ddddddddddd/ .dddddddddddddhddddddddddddddddyhddddddddd.")
		print("      sddyoooosddddhooooohddddooooohddddsoooosd+  shhsoooosddh` +ddoooooydh` /ddhooooohdd: .dhooooohddddoooooyddddyoooosyyhdhoooooddd.")
		print("      shy/-  `/ddddy:   :hdddh:`  -sdddd/.  :+d+  ydd+-  -/ddh` +dh:`  :sdh` :yys-   :hdd: `dh:   :ydddd/`  :oddddo-  ./hdddy:   :ddd.")
		print("      ooy+-  `:hdddy:   :hdddh:   -sdddd/.  -/h/  ydd+-  ./ddh  +dd:`  -sdh` -yys-   :hdd: `hh:   :ydddd/`  :oddddo.  .+ddddy:   :ddd.")
		print("      ooh/:  `:hdddy:   :hdddh:   -sdddd/.  -/h+  ydd+-  ./ddy  /dd:`  -sdh` .yys-   -hdd-  hh:   :ydddd/`  :odddh+.  .+ddddy:   :ddh.")
		print("      shs+:--:+ddddh/:::/hdddh/:::/ydddd+:::/od/  yddo/::/+ddy  /dd/:::/sdh  -sys:-::/hdd-  hh/:::/hdddd+:::/sdhhyo/::/+ddddy/:::/ddd.")
		print("      sddddddddddddddddddddddddddddddddhhhhdddd/  sddddddddddy  /dddddddddh  -ddddddddddd-  hddddddddddddddddhhhhhddddddddddddddddddd.")
		print("      sddhyyyyhddddhyyyyydddddyyyyyhdddhyyyyyhd/  sddhyyyyhdds  :ddyyyyyhdy  -dddyyyyyddd-  hdyyyyyhddddhyyyyyhdddhyyyyhddddhyyyyyddd.")
		print("      sddo:``./ddddy:.`.:hdddh:.``-sdhdd/-``:+d/  sdd+-``-/dds  :dd:.``:ohy  .ddh:``.:hdd.  yh:.`.:ydddd/.``:oddddo-``-+dddds:.`.:ddd.")
		print("      sddo:  `/ddddy:   :hdddh:   -sdddd/.  -+d:  odh+-  ./ddo  :dd:`  -sds  .ddh:   :hdh.  yh:   :ydddd/`  :oddddo.  .+dddds:   :ddd.")
		print("      sddo:  `/ddddy:   :hdddh:   -sdddd/.  -+d:  odd+-  ./ddo  -dd:`  -sds  .hdh:   :hdh.  yh:   :ydddd/`  :oddddo.  .+ddddy:   :ddd.")
		print("      sddo:.../ddddy:...:hdddh:...-sdddd/-..:+d:  odd+:..-/ddo  -dh:`  -sds  .hdh:...:hdh.  yh:...:ydddd/...:odddd+-..-/ddddy:...:ddd.")
		print("      sddhhyhhhdddddhhhhhddddhhhhhhdddddhhhhhhh:  +ddhhhhhhddo  -dd:`  :sds  .hddyyhhhddh.  sdhhhhhhddddhhhhhhddddhhyyhhdddddhhhhhddd.")
		print("      sddhddddddddddddddddddddddddddddddddddss++ssssssssssssssosssssssssssssssssssssssssssss/ssyddddddddddddddddddddddddddddddddddddh.")
		print("      sdddddddhddddddddddhddddddddddddddddoo/sssssssssssssssosssssssssssssssssosssssossssssssso++hddddddddddddddddddddddddddddddddddd.")
		print("      .-----------------------------------.-----------------------------------------------------.------------------------------------`")

	elif room["name"] == "the Trump Tower":
		print("              .yyyyyyyyyyyyyy`     ///////////:-`       /+++/      /+++/      -++++++`     :+++++/      ://////////:.`   ")
		print("              -MMMMMMMMMMMMMM`     NMMMMNNNNNMMMm+      NMMMd      NMMMm      +MMMMMMs    -NMMMMMm      mMMMMNNNNMMMMd-  ")
		print("              `////yMMMMs////      NMMMm...--mMMMM`     NMMMd      NMMMm      +MMMMMMM+  .mMMMMMMm      mMMMN----/MMMMh  ")
		print("                   +MMMM/          NMMMNhhhhdMMMMy      NMMMm      NMMMm      +MMMMsMMN-`hMMymMMMm      mMMMNyyyydMMMN+  ")
		print("                   +MMMM/          NMMMNhhdMMMMy-       NMMMm     `NMMMd      +MMMM-sMMmyMMm`mMMMm      mMMMMddddddho-   ")
		print("                   +MMMM/          NMMMd  `yMMMN+       yMMMMy/::/hMMMMo      +MMMM-`dMMMMN- mMMMm      mMMMm            ")
		print("                   /mmmm/          mNNNh   `oNNNmo      `+hmNMMMMMMNmh/       +mmmm- .mmmm/  hmmmh      dNNNd            ")
		print("                   ``````          ....`     .....         `..----..`         `````   ````   `````      .....            ")

	elif room["name"] == "the Trump Vault":
		print("                                                                       .+yhhhyo-              ")
		print("                                                                    `/dh+.   `:dy             ")
		print("                                                               `:+syms-        /M`            ")
		print("                                                             .ymyo/-`         `mmhs:          ")
		print("                                                           .:hN.             .dy``:hh`        ")
		print("                                                         `dNMMN.    -       -mo    :M-        ")
		print("                                                         :MMMMMm.   s      /m/   -omo         ")
		print("                                                          /hNMMMm:-.d:    om-./shy+.          ")
		print("                                                           `.:+ddoosmNs+odMMdyo:.             ")
		print("                                                             .oys+/:---:/+sdd.                ")
		print("                                                             od-:+syddmdho/:ys                ")
		print("                                                           `-smyo/+Ns:-oN/+shy-               ")
		print("                                                         .+hy/.``:o-    /y``-sdy:`            ")
		print("                                                       -ydo.    ..       .+.  .+hd/`          ")
		print("                                                     .ydo.        `.  .-   .`   `/hd/`        ")
		print("                                                   `oms.          +m+-mN-         `/dh:       ")
		print("                                                  -dd:          :smMNNMMmho`        `oms`     ")
		print("                                                 +Ns`          oMMmMm:hMdyd-          -dd-    ")
		print("                                                oN+            mMN:MN +My              `ym:   ")
		print("                                               oN/             sMMhMMoyMd.`             `yN.  ")
		print("                                              /M+               :shNMmmMMNh+`            `ms  ")
		print("                                             `md                   dM:.MNoNMy             +N- ")
		print("                                             :M/               `.` hM/`NN`hMM.            .Ms ")
		print("                                             /M:              `hNmydMo.NMoNMm`             Ny ")
		print("                                             :M+               odNNMMMNMMMNy.          `  `Nsz")
		print("                                             `md`                .-yMhoNM/.           :.  :M: ")
		print("                                              :Ny`                 :y: +o`          `o:  .my  ")
		print("                                               :Nd-       .`                      `+h-  :my`  ")
		print("                                                .sNh/`    `/s/.                `/ymo.:odh:    ")
		print("                                                  .+dNdy++++odMmho+:-.....-:/sdMNNmdhs/.      ")
		print("                                                     `-:+sssso+::+oshhdddhysoo/-              ")

	elif room["name"] == "Satan's Bar":
		print("                                                                                                                           `....            ")
		print("                                                                                                                       .+hmmmmmmds:         ")
		print("                                                                                              `y`                     :mNNNNNNNds:.o`       ")
		print("   :+//////////////////////////////////////////////////////////////////////////////////////-  +my:                    +NNmmmmmds-`-ys       ")
		print("  y/```````````````````````````````````````````````````````````````````````````````````````s:.`ymy+`                .o.dmNmhmmdh/+hNy       ")
		print("  d          ..:/++.        `...       `.-://++oo+                             :ys.        :/`-hmdy+                .yhmNmhhdmNmhdNN+       ")
		print("  d      ./oyhhhyss:      -oyhhh+`  .syhhhyysssoo+    `.-.                    +hh+`        :/  .-/ds/                .shhhhhhhmmmNNy`       ")
		print("  d    :shhs+:.``        +hho--hho   -/:./+/`     ./syyhhho      /-     ``   `:/-          :/    .mhs-                .yhhysyhmNNNy`-++     ")
		print("  d   /hho.`           `shh:   /dh.      sdh     /hhs/:-odh    -hNh-   :yy-     `.-:/os-   :/    `mdyo-            ss+::yhhhyhmNNm.+yhN-    ")
		print("  d   -yhy+-`         `sdy-````:dd-      sdh    /hh+`   +dd`  `sNNy  .ohh+` `:oyyhhysso.   :/     hddys.          `mmsyommddhhmNNN++ood-    ")
		print("  d    `:syhyyo+:.`   /ddhyyyyyhmd-      sdh   `hdh/++oodmh   odmdh.:yds-  `shdo:-.``      :/     :mddys-          +y/ymddhhyyddhhdmdo/     ")
		print("  d       `.:+syhhyo..hdo//////sdd-      hds   +ddysssoymm+  /hhoddyhh+`   .yhdy+-`        :/      +mmdhs/`        .:ydhhyyyydhyyyymh+-:-   ")
		print("  d            `.-ydy+dd.      sdh      .dd/  `hds``   sdy` `hds`hmNh:      `.:ohhs:       :/       :ydmhso-       +/hhhhyydmdyyyyh:.osoy-  ")
		print("  d    `...``` ``./ddodd-     .hd+      odh.  -dd:    /dh:  -yh: :oo:           .+dh:      :/        `/dmdyo+-     +mNmmy-omNmhhyyy.yos:y+  ")
		print("  d    :hhhyssssyhhy+.hy/     `:/.      /o/   :sy`    .:/   ``.      `.`````````.:dd/      :/       .+shmmdds+/.    hhhdmdmNNmmdyys+h-yys+  ")
		print("  d    `.--//////:.`  .`                        `                    +hyyyyyyyyyyhhs.      :/      ./sdmmmmddyo//.  oyyyhhdddy:hyy+oh`.:/.  ")
		print("  d`                                                                 .-:::::::::--.        :/     ./sdmmmmmmddds//:`/yyyyyhs-  shys-h/      ")
		print("  /o-.....................................................................................:s.    .+ydmmhmmmmmmddhohsyyyyyh+`   +hyy`oy:     ")
		print("   `::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::-`    -ohdmmo`smmmmmds//hdhhyyyhy-   :hyh.-ho     ")
		print("                                                                                              `/ydmds-  `smddmy/-:syymmmdsmh`  `yyh-+y/     ")
		print("                                                                                             -sddy/.     `ododhhyyyyyydd++Nms`  /hhsyy`     ")
		print("                                                                                           `+hdh:          :shdhhyyyyyyh/mmhyy:.-hyhhso+:`  ")
		print("                                                                                           +hmd`             :ohhhyyyyyhdd/ -+sss+osyy+/+:  ")
		print("                                                                                          :sdyy                 .-:++++/-`            `     ")
		print("                                                                                          oy/ .                                             ")
		print("                                                                                         .-`                                                ")

	elif room["name"] == "the Trump Office":
		print("                                                                            ..` .-/:-  ....                                                 ")
		print("                                                                           :oso:y/h+/://:::-o....                                           ")
		print("                                                                         `./+oy/hoo/+yssso+sys/-:--`                                        ")
		print("                                                                        `:y/+yos+o:--``  `.--:ooyh::-+/-.                                   ")
		print("                                                                         -+o/oo/.              ./+o/so/y:                                   ")
		print("                                                                        `-:o+/-        `         .++yss++.                                  ")
		print("                                                                       `:-yo-`       ` .          `+/o/oo:.                                 ")
		print("                                                                       `::s:/        ` . .         .+oh++y:-                                ")
		print("                                                                        /ss:.        ``` `          o:o+ss:.                                ")
		print("                                                                        :os:-         . .           +:h::.`                                 ")
		print("                                                                       .:-s:+         . `           o+h+-`                                  ")
		print("                                                                       `:-yy::        .            -+s:/-                                   ")
		print("                                                                        `-:+o:/       `           :ohys-                                    ")
		print("                                                                        .:ss:y+/:`             `:+++//s:    (this is a mirror)              ")
		print("                                                                        .:y+oy+o++::-.`   `.:-/syy+hyd.+                                    ")
		print("                                                                         ..-:y/sso++osoo+oosso/osss/od-o:                                   ")
		print("                                                                             .-y+oy:-/++-/smh`hh:+s+ys:/o`                                  ")
		print("                                                                              ..:/-. .....:+s/:+oooo/y--:o                                  ")
		print("                                                                                              .:+so:::s:ym:                                 ")
		print("                                                                                                  -//yhyy+//.                               ")
		print("                                                                                                     `/o:--:+/`                             ")
		print("                                                                                                        :+:..:+:`                           ")
		print("                 `:+yyyy+:`      -////////.   :////////`  .//       `/oyyy+:`   ./////////`              .+/-.-:+/-                         ")
		print("               .yMNhoooshMMs`    yMmyyyyyy:  `NMhyyyyyy.  /MN`    :hMmyoooymN-  oMmoooooo+`                +/..`-:os:`.`                    ")
		print("              -mMs`      .dMd`   yMo         `NN-         /MN`   /NM+       -`  oMd                         ++.-::o/s+:/                    ")
		print("              dMh         .NM+   yMo         `NN-         /MN`  `NMs            oMd                          /hs:osmh+//.                   ")
		print("             `NMo          dMy   yMdssssso`  `NMysssss+   /MN`  :MN:            oMNmmmmmd.                   ./+shhmm/-/-                   ")
		print("             `NMo          mMs   yMy::::::`  `NM+:::::-   /MN`  :MM:            oMd``````                     :+/:-:hmdddo                  ")
		print("              hMd`        /MN-   yMo         `NN-         /MN`  `NMy            oMd                            `.-::mh``dd`                 ")
		print("              .mMd-     `+NN+    yMo         `NN-         /MN`   /NMy.     -+.  oMd                                 +hdhy:                  ")
		print("               `omMmhhhmNNs-     yMo         `NN-         /MN`    .sNMmhhhmNh.  oMNhhhhhhh-                                                 ")
		print("                  `-:::-`        `.`          ``           .`        .::::.`     ........`                                                  ")
	elif room["name"] == "Trump's limo":
		print("                                            `:/:::::::/dddmmmhy+///++++++/////////////:::+ydd+-----::-::::-``                               ")
		print("                                        `-+/:`        sMMMMMMo/                         .+mMM:          `-+dmhs/.    `                      ")
		print("                                    `./++-`          -NMMNMMm:-                         -+MNM-           . `yMNMNy:` -                      ")
		print("                         ````````.:ohNd:            `dMMNMMMo                            sNMM.           `  `MNMMMMh--``                    ")
		print("        `...--://+ossyyhhdddddmmmNMmdMMdssyyyyyyyyyyhMMNNMMMdyyyyyyyyyyyyyyyyyyyyyyyyyyyyNNMMhhhyyyyyyyyyhyyhMmMMMMMNmdhhhyso+/:-..`        ")
		print("    -+syyddNMMNNNNMNNNNNNNMMMMNNNNNNNMMMMMMMNNNNmmmmNMMmMMMMMMNNNNNNNNNNNNMNNNNNNNNNNNNNNNmNNNNNNNNNNNMNmmmmNMmNNNNNNMMNNNNNMNNMMNmo:.      ")
		print("   /+:-.-:+NNNMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMNmmmNMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMNmmmNNNMMMMMMMMMNyhNMMMMMMMm::.     ")
		print(" -odhhhhddmMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMNdmMMMMMMMMMmhs.    ")
		print("`mMMMMMMMMMMMMMMmy+/oyNMMMMMMNNNNmNNNNNNNNNNNNNNNNNNNNNmNNmNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNmNNNNNNNNNNNNNNNNMMmyo/+ymMMMMMMMMMMMMNMMMMMMMNh`  ")
		print("`mNNNNNNNNMMMMMd-.....-mMMMMMNmmmmmmmmmmmmmmmmdddddddddhhhhhhhhhhhhhhhhhhhddddddddddddmmmdmmmmmmmmmmmmmmNMMm-.....-dMMMMmmmmmmmmNmNNNNMMM.  ")
		print(" -+oshdmmNMMMMMy`..`..`yMMMNNMMMMMMMMMNNNmmdddhhyyysssoo++++////::::::::////+++ooossyyyhhhddmmmNNNMMMMMNMMMy`..``.`yMMMMMMMMMMMMMMMMMMNmh   ")
		print("      `````+MMMMs-...-sMMMMo/+++++++++++++++++++++///////////:::::::::://////////++++++ooooooosssssssss+yMMMs-...-sNMMmsssoo+++//::-..``    ")
		print("            :dMMMNNmNNMMMm/                                                                              +mMMNNmNNMMNs`                     ")
		print("              -ohmNNNmho-                       `                                                          -oyhddyo/`                       ")
