print()
print("                                                                                                                           `....            ")
print("                                                                                                                       .+hmmmmmmds:         ")
print("                                                                                              `y`                     :mNNNNNNNds:.o`       ")
print("   :+//////////////////////////////////////////////////////////////////////////////////////-  +my:                    +NNmmmmmds-`-ys       ")
print("  y/```````````````````````````````````````````````````````````````````````````````````````s:.`ymy+`                .o.dmNmhmmdh/+hNy       ")
print("  d          ..:/++.        `...       `.-://++oo+                             :ys.        :/`-hmdy+                .yhmNmhhdmNmhdNN+       ")
print("  d      ./oyhhhyss:      -oyhhh+`  .syhhhyysssoo+    `.-.                    +hh+`        :/  .-/ds/                .shhhhhhhmmmNNy`       ")
print("  d    :shhs+:.``        +hho--hho   -/:./+/`     ./syyhhho      /-     ``   `:/-          :/    .mhs-                .yhhysyhmNNNy`-++     ")
print("  d   /hho.`           `shh:   /dh.      sdh     /hhs/:-odh    -hNh-   :yy-     `.-:/os-   :/    `mdyo-            ss+::yhhhyhmNNm.+yhN-    ")
print("  d   -yhy+-`         `sdy-````:dd-      sdh    /hh+`   +dd`  `sNNy  .ohh+` `:oyyhhysso.   :/     hddys.          `mmsyommddhhmNNN++ood-    ")
print("  d    `:syhyyo+:.`   /ddhyyyyyhmd-      sdh   `hdh/++oodmh   odmdh.:yds-  `shdo:-.``      :/     :mddys-          +y/ymddhhyyddhhdmdo/     ")
print("  d       `.:+syhhyo..hdo//////sdd-      hds   +ddysssoymm+  /hhoddyhh+`   .yhdy+-`        :/      +mmdhs/`        .:ydhhyyyydhyyyymh+-:-   ")
print("  d            `.-ydy+dd.      sdh      .dd/  `hds``   sdy` `hds`hmNh:      `.:ohhs:       :/       :ydmhso-       +/hhhhyydmdyyyyh:.osoy-  ")
print("  d    `...``` ``./ddodd-     .hd+      odh.  -dd:    /dh:  -yh: :oo:           .+dh:      :/        `/dmdyo+-     +mNmmy-omNmhhyyy.yos:y+  ")
print("  d    :hhhyssssyhhy+.hy/     `:/.      /o/   :sy`    .:/   ``.      `.`````````.:dd/      :/       .+shmmdds+/.    hhhdmdmNNmmdyys+h-yys+  ")
print("  d    `.--//////:.`  .`                        `                    +hyyyyyyyyyyhhs.      :/      ./sdmmmmddyo//.  oyyyhhdddy:hyy+oh`.:/.  ")
print("  d`                                                                 .-:::::::::--.        :/     ./sdmmmmmmddds//:`/yyyyyhs-  shys-h/      ")
print("  /o-.....................................................................................:s.    .+ydmmhmmmmmmddhohsyyyyyh+`   +hyy`oy:     ")
print("   `::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::-`    -ohdmmo`smmmmmds//hdhhyyyhy-   :hyh.-ho     ")
print("                                                                                              `/ydmds-  `smddmy/-:syymmmdsmh`  `yyh-+y/     ")
print("                                                                                             -sddy/.     `ododhhyyyyyydd++Nms`  /hhsyy`     ")
print("                                                                                           `+hdh:          :shdhhyyyyyyh/mmhyy:.-hyhhso+:`  ")
print("                                                                                           +hmd`             :ohhhyyyyyhdd/ -+sss+osyy+/+:  ")
print("                                                                                          :sdyy                 .-:++++/-`            `     ")
print("                                                                                          oy/ .                                             ")
print("                                                                                         .-`                                                ")